services:
  <TEMPLATE_DEV_BOX_NAME>:
    restart: always
    image: ${PLUGIN_DEVBOX_INIT_SERVICE_IMAGE}
    command: sleep infinity
    environment:
      # oh-my-zsh
      # PROMPT: "[devbox] $PROMPT"
      # bash
      PS1: "[devbox] $PS1"

networks:
  default:
    external: true
    name: $PLUGIN_DEVBOX_INIT_SERVICE_NETWORK
    