#!/bin/bash

help() {
  echo "Usage:"
  echo "  devbox create <name> <code_dir>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local code_dir=$2

  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  if [ -z "$code_dir" ]; then
    os::inquirer code_dir "text" "You code directory?" true
  fi

  devbox::create $name $code_dir
}

run() {
  core $@
}

run $@
