#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_DEVBOX_NAME)
  echo "DevBox ($(color::success $version))"
}

description() {
  echo "Instant, easy, and predictable development environments."
}

usage() {
  echo "Usage:"
  echo "  devbox init                 - Initialize a directory as a devbox project"
  echo "  devbox add <language>       - Add a language, such as nodejs,go,rust,python,java,deno"
  echo "  devbox shell <name>         - Start a new shell or run a command with access to your packages"
  echo "  devbox create <name>        - Create a new devbox"
  echo "  devbox remove <name>        - Remove a devbox"
  echo "  devbox ls                   - List all devboxes"
  echo "  devbox inspect <name>       - Inspect a dexbox"
  echo "  devbox help                 - Show help"
}

example() {
  echo "Example:"
  echo "  devbox init"
  echo "  devbox add nodejs"
  echo "  devbox shell"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
