#!/bin/bash

help() {
  echo "Usage:"
  echo "  devbox list"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local devboxes=$(devbox::list)
  local count=0
  for name in $devboxes; do
    count=$((count + 1))
  done

  log "  total: $(color::success $count) (includes init)"
  log ""

  local index=0
  for name in $devboxes; do
    index=$(number::step index)

    if [ "$name" = "$PLUGIN_DEVBOX_INIT_NAME" ]; then
      log "    ${index} init $(color::success "[builtin]")"
    else
      log "    ${index} $name"
    fi
  done
}

run() {
  core $@
}

run $@
