#!/bin/bash

# devbox::stop stops a new dev environment.
devbox::stop() {
  local name="$1"
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    return 1
  fi

  local err_log="$(os::tmp_file)"
  local service_dir="$PLUGIN_DEVBOX_SERVICES_DIR/$name"
  local service_name="${PLUGIN_DEVBOX_INIT_SERVICE_NAME_PREFIX}${name}"
  local service_docker_compose=${service_dir}/docker-compose.yml

  if [ ! -d "$service_dir" ]; then
    log::info "[$(timestamp)] devbox($name) stopped before."
    return 0
  fi

  cd $service_dir

  # stop service
  docker-compose down --remove-orphans # >>/dev/null 2>$err_log
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to stop devbox: $name."
    # cat $err_log
    return 1
  fi

  log::success "[$(timestamp)] succeed to stop devbox: $name."
}

export -f devbox::stop
