#!/bin/bash

help() {
  echo "Usage:"
  echo "  devbox service start <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    local options=($(dexbox::list))
    os::inquirer name "select" options "Select an service ?" true
  fi

  devbox::start $name
}

run() {
  core $@
}

run $@
